apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ${{ values.vmName }}-dv
  namespace: ${{ values.namespace }}
spec:
  sourceRef:
    kind: DataSource
    name: fedora
    namespace: openshift-virtualization-os-images
  storage:
    resources:
      requests:
        storage: 40Gi
