apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ${{ values.vmName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.vmName }}
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: ${{ values.vmName }}
        app: ${{ values.vmName }}
    spec:
      domain:
        resources:
          requests:
            cpu: ${{ values.cpu }}
            memory: ${{ values.memory }}
          limits:
            cpu: ${{ values.cpu }}
            memory: ${{ values.memory }}
        devices:
          disks:
            - diskbus: virtio
              name: containerdisk
            - diskbus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          dataVolume:
            name: ${{ values.vmName  }}-dv
            options:
              sourceRef: 
                kind: DataSource
                name: fedora
                namespace: openshift-virtualization-os-images
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: dirk
              password: password:redhatocp
              chpasswd: { expire: False }
              sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
              packages:
                - httpd
              write_files:
                - content: |
                    <html>
                    <body>
                      <h1>You are now viewing Dirk's Golden Image</h1>
                      <p>Hosted on <strong>OpenShift Virtualization</strong> via Cloud-Init</p>
                    </body>
                    </html>
                  path: /var/www/html/index.html
              runcmd:
                - [ systemctl, enable, --now, httpd ]
     
          name: cloudinitdisk

